type Scalar = string | number | boolean | Date | null | undefined;

function yamlScalar(v: Scalar): string {
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  if (typeof v === "string") return JSON.stringify(v);
  return String(v);
}

export function frontmatter(fields: Record<string, Scalar | Scalar[]>): string {
  const lines = ["---"];
  for (const [k, v] of Object.entries(fields)) {
    if (v === undefined) continue;
    lines.push(Array.isArray(v) ? `${k}: [${v.map(yamlScalar).join(", ")}]` : `${k}: ${yamlScalar(v)}`);
  }
  lines.push("---", "");
  return lines.join("\n");
}

const NOTICE = "> Read-only. Generated from the knowledge base; edits here are overwritten on the next projection.\n";
const link = (name: string) => `[[${name}]]`;

/**
 * Evidence quotes are verbatim source text on one line. Escape "[[" and a "#" that starts a word so a quote
 * cannot create a stray link, embed or tag.
 */
function escapeQuote(text: string): string {
  return text.replace(/\s+/g, " ").trim().replace(/\[\[/g, "\\[\\[").replace(/(^|\s)#/g, "$1\\#");
}

export interface NodeView {
  id: string;
  type: string;
  name: string;
  noteName: string;
  aliases: string[];
  properties: Record<string, unknown>;
  verified: boolean;
  isSelf: boolean;
  edges: { direction: "out" | "in"; type: string; otherNoteName: string; evidence: string | null; evidenceDocNoteName: string | null }[];
  mentionedIn: { docNoteName: string; kind: string; date: string | null }[];
  facts: { predicate: string; objectText: string; verified: boolean; by: string | null; docNoteName: string | null }[];
}

export function renderNode(n: NodeView): string {
  const tags = [`brain/node/${n.type}`, ...(n.verified ? [] : ["brain/unverified"])];
  const out = [
    frontmatter({ brain_id: n.id, brain_type: n.type, brain_managed: true, aliases: n.aliases, verified: n.verified, tags }),
    `# ${n.name}`,
    "",
    NOTICE,
  ];
  if (n.isSelf) {
    out.push("## Facts");
    out.push(n.facts.length ? n.facts.map((f) => `- ${f.predicate}: ${f.objectText} (${f.verified ? "verified" : `unverified, ${f.by ?? "unknown"}`}${f.docNoteName ? `, from ${link(f.docNoteName)}` : ""})`).join("\n") : "- none yet");
    out.push("");
  }
  out.push("## Relationships");
  out.push(
    n.edges.length
      ? n.edges
          .map((e) => {
            const arrow = e.direction === "out" ? "→" : "←";
            const ev = e.evidence ? ` · "${escapeQuote(e.evidence)}"${e.evidenceDocNoteName ? ` (${link(e.evidenceDocNoteName)})` : ""}` : "";
            return `- ${e.type} ${arrow} ${link(e.otherNoteName)}${ev}`;
          })
          .join("\n")
      : "- none",
  );
  out.push("", "## Mentioned in");
  out.push(n.mentionedIn.length ? n.mentionedIn.map((m) => `- ${link(m.docNoteName)} (${m.kind}${m.date ? `, ${m.date}` : ""})`).join("\n") : "- none");
  const props = Object.entries(n.properties);
  if (props.length) {
    out.push("", "## Properties");
    out.push(props.map(([k, v]) => `- ${k}: ${typeof v === "string" ? v : JSON.stringify(v)}`).join("\n"));
  }
  return out.join("\n") + "\n";
}

export interface DocView {
  id: string;
  noteName: string;
  title: string | null;
  kind: string;
  origin: string | null;
  occurredAt: Date | null;
  ingestedAt: Date;
  summary: string | null;
  entityNoteNames: string[];
  raw: string;
}

export function renderDocument(d: DocView, maxChars = 200_000): string {
  const body = d.raw.length > maxChars
    ? d.raw.slice(0, maxChars) + `\n\n> (truncated at ${maxChars} characters; the full ${d.raw.length}-character text is in the knowledge base as document ${d.id})\n`
    : d.raw;
  return [
    frontmatter({ brain_id: d.id, brain_kind: d.kind, brain_managed: true, origin: d.origin ?? undefined, occurred_at: d.occurredAt ?? undefined, ingested_at: d.ingestedAt, tags: [`brain/document/${d.kind}`] }),
    `# ${d.title ?? "(untitled)"}`,
    "",
    NOTICE,
    d.summary ? `**Summary.** ${d.summary}\n` : "",
    d.entityNoteNames.length ? `**Entities.** ${d.entityNoteNames.map(link).join(" · ")}\n` : "",
    "---",
    "",
    body,
  ].filter((s) => s !== "").join("\n") + "\n";
}

export function renderReadme(counts: { nodes: number; documents: number }, generatedAt: Date): string {
  return [
    frontmatter({ brain_managed: true, generated_at: generatedAt.toISOString() }),
    "# Brain",
    "",
    `This folder mirrors the knowledge base: ${counts.nodes} entity notes under \`nodes/\` and ${counts.documents} document notes under \`documents/\`. It is regenerated by \`brain project-obsidian\`; edits here are overwritten. Generated ${generatedAt.toISOString()}.`,
    "",
    "Graph view tips: filter with `path:Brain`; add color groups such as `path:Brain/nodes/person`, `path:Brain/nodes/organization`, `path:Brain/documents`, or `tag:#brain/unverified`.",
    "",
  ].join("\n");
}
